### ISSUE TITLE
Possible to switch Raumfeld Connector to line in?

### ISSUE THREAD

**Issue by bjornhij** [maierp/PyRaumfeld#2]
I cannot find a function to switch the Raumfeld Connector to line in. I can implement it, if I know the correct SOAP remote procedure. Did somebody reverse engineer this already?

**Comment by maierp** [comment]
Hi Bjorn,

> I cannot find a function to switch the Raumfeld connector to line in. I
> can implement it, if I know the correct SOAP remote procedure. Did
> somebody reverse engineer this already?

I think therefore you have to browse the raumfeld media server, where 
the line-in should be, as well as TuneIn and Wimp etc.

Greets
Patrick

**Comment by tilltnet** [comment]
It's integradted in [rf.wr](https://github.com/tilltnet/rf.wr.py) - which uses PyRaumfeld.

If you want to do it yourself: basically as Patrick said, the Line-In is simply a container on the media server. The container adress is '0/Line In'. Browse the children of that adress and you will get all Line-Ins available (e.g. connector and other Raumfeld devices).

**Comment by bjornhij** [comment]
Thanks, browse_children works, and I can now switch to Line In.
