### ISSUE TITLE
How to controll

### ISSUE THREAD

**Issue by quintz** [maierp/PyRaumfeld#3]
Hi 

i managed to install it like you said to me over at the other Raumfeld Project (https://github.com/tfeldmann/python-raumfeld/issues/10) but how do I controll it then?

Could you make a little How To maybe?

Cheers

quintz

**Comment by maierp** [comment]
Hi quintz,
as I wrote in the readme file, there is a sample program how to use the library (PyRaumfeldSample.py) and a program (RaumfeldControl.py) which provides a web-based API to the Raumfeld system.

When you run the RaumfeldControl.py, and connect to **`http://localhost:8080`** you will get the index page with the supported web commands.
For example **`http://localhost:8080/zones`** will return the list of zones in JSON fromat.
If you have a room with the name "kitchen", you can set the volume of that room to 50 by calling: **`http://localhost:8080/room/kitchen/volume/50`**

Hope this helps
Greets
Patrick

**Comment by quintz** [comment]
Thanks Patrick,
now it works perfectly :+1:  :)

Now I only have to get it into my automatization rules in my pimatic and everythings nice!

**Comment by maierp** [comment]
Great that it works. If you have further questions, just ask :)
Greets
Patrick
